spring.application.name=courseplatform-backend
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/onlinecourse
spring.datasource.username=postgres
spring.datasource.password=Raghav@911
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true